### ISSUE TITLE
Providing License.

### ISSUE THREAD

**Issue by Dennis-Kluge** [renevanderark/goharvest#2]
Hello, 

I just found goharvest and would like to use it in a project. Unfortunately there is no license information provided which means that goharvest is proprietary and not allowed to use in other projects. 

Could you please add a license. 

Thank you advance and best regards from Berlin, 
Dennis.

**Comment by renevanderark** [comment]
Hello Dennis,

I have added the MIT license. I hope this project suits your needs. I must however warn you that I only wrote this to teach myself a little golang. It should be pretty compliant to the OAI-PMH spec, though.

Best, 
René

**Comment by Dennis-Kluge** [comment]
Thank you for your effort and quick answer. :)
